language: csharp
solution: NextLevelSeven.sln
sudo: false
addons:
  apt:
    packages:
    - nunit-console
script:
  - xbuild /p:Configuration=Debug NextLevelSeven.sln
before_script:
  - nuget restore NextLevelSeven.sln
after_script:
  - nunit-console NextLevelSeven.Test/bin/Debug/NextLevelSeven.Test.dll
